server:
  port: 8081
  servlet:
    context-path: /api


spring:
  application:
    name: PROVA-SERVICE
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka




